# A sample Gemfile
source "https://rubygems.org"

gem 'rubocop'
gem 'ruby-debug-ide'
gem 'debase'
gem 'rcodetools'
gem 'fastri'

gem 'sinatra'
gem 'sinatra-contrib'
#gem 'lazy_high_charts'
gem 'sinatra-activerecord'

gem 'rake'

gem 'pry'

group :production do
  gem 'pg' , '~> 0.18'
end

group :development do
  gem 'sqlite3', '~> 1.3.6'
end
gem 'bcrypt'
